/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Usuario' at '12/01/17 16:32' with Gradle 3.2.1
 *
 * @author Usuario, @date 12/01/17 16:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
